'use strict';

const path = require('node:path');
const fs = require('node:fs');

/** Package root (the directory holding package.json). */
const PACKAGE_ROOT = path.resolve(__dirname, '..');

/** Where the extracted .app bundle lives. Never published to npm. */
const VENDOR_DIR = path.join(PACKAGE_ROOT, 'vendor');

/** The notarized bundle, extracted verbatim from the release tarball. */
const APP_PATH = path.join(VENDOR_DIR, 'MacControlMCP.app');

/** The stdio MCP server executable inside the bundle. */
const BINARY_PATH = path.join(APP_PATH, 'Contents', 'MacOS', 'MacControlMCP');

/** The bundle's Info.plist — source of truth for the installed version. */
const INFO_PLIST_PATH = path.join(APP_PATH, 'Contents', 'Info.plist');

/**
 * Read a top-level string value out of an XML plist without pulling in a
 * parser dependency. The bundle's Info.plist is generated by our own build
 * script, so its shape is known and stable.
 *
 * @param {string} xml
 * @param {string} key
 * @returns {string|null}
 */
function readPlistString(xml, key) {
  if (typeof xml !== 'string') return null;
  const escaped = key.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
  const re = new RegExp(`<key>\\s*${escaped}\\s*</key>\\s*<string>([^<]*)</string>`);
  const m = re.exec(xml);
  return m ? m[1].trim() : null;
}

/**
 * Version of the currently installed .app bundle, or null when the bundle is
 * absent or unreadable.
 *
 * @param {string} [plistPath]
 * @returns {string|null}
 */
function installedVersion(plistPath = INFO_PLIST_PATH) {
  try {
    const xml = fs.readFileSync(plistPath, 'utf8');
    return readPlistString(xml, 'CFBundleShortVersionString');
  } catch {
    return null;
  }
}

/**
 * @returns {boolean} whether the launcher has something to exec.
 */
function isInstalled(binaryPath = BINARY_PATH) {
  try {
    return fs.statSync(binaryPath).isFile();
  } catch {
    return false;
  }
}

module.exports = {
  PACKAGE_ROOT,
  VENDOR_DIR,
  APP_PATH,
  BINARY_PATH,
  INFO_PLIST_PATH,
  readPlistString,
  installedVersion,
  isInstalled,
};
